#
POST https://grades-api-cleber.herokuapp.com/grade
Content-Type: application/json

{
"name":"Pablo",
"subject": "React",
"type" : "Desafio",
"value": 200,
"lastModified": "data"

}
###





DELETE http://localhost:3000/accounts/removeandshownumberaccounts/33/9101

###
PUT http://localhost:3000/accounts/transfer/1017/9102/150
Content-Type: application/json

{



}
###
get https://grades-api-cleber.herokuapp.com/grade/

###